default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] %>
  username: postgres
  password:
  pool: 5

production:
  <<: *default
  database: skills_app_db_1

development:
  <<: *default
  database: skills_app_db_1

test:
  <<: *default
  database: skills_app_db_1