# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 360129cc295aa290f15472fcdae62e2a9c89594d1cf0f36aa8de84a5eb7603cb72b8809daec4da99f9acf89c0e01f6e147fa4ce6d4eb586d89604249e8844152

test:
  secret_key_base: 7e6b1b3328bc2881dc774d231d4ee12a80b289d81d2dc87cffac3adba63c38ac19a86e584e10604d0369cc8785a367e6c5cb74599719a27066c676dbc120453e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
